'use client';

import { useState } from 'react';
import { FileText, Download, Copy, Check, ExternalLink, Package } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { mockArchitectureReport } from '@/lib/mock-data';

const architectureMarkdown = `# Architecture Report: fastapi-example

## Overview

This is a **production-ready FastAPI application** with authentication, user management, and project features. The codebase follows a layered architecture pattern with clear separation of concerns.

## Tech Stack

### Languages
- Python 3.11

### Frameworks
- **FastAPI** - Modern, fast web framework for building APIs
- **SQLAlchemy** - SQL toolkit and ORM
- **Pydantic** - Data validation using Python type annotations

### Databases
- **PostgreSQL** - Primary relational database
- **Redis** - Caching and session storage

## Architecture Pattern

The application follows a **Layered Architecture (Clean Architecture)** pattern with the following layers:

1. **API Layer** (\`src/api/\`)
   - Route handlers
   - Request/response schemas
   - Dependency injection

2. **Service Layer** (\`src/services/\`)
   - Business logic
   - Data transformation
   - External service integration

3. **Data Layer** (\`src/models/\`)
   - SQLAlchemy models
   - Database operations

## Key Entry Points

| File | Description |
|------|-------------|
| \`src/main.py\` | FastAPI application entry point |
| \`src/api/routes/__init__.py\` | API router aggregation |

## Dependencies

### External Dependencies

| Package | Version | Purpose |
|---------|---------|---------|
| fastapi | 0.109.0 | Web framework |
| sqlalchemy | 2.0.25 | Database ORM |
| pydantic | 2.5.3 | Data validation |
| python-jose | 3.3.0 | JWT handling |
| passlib | 1.7.4 | Password hashing |
| redis | 5.0.1 | Caching |

### Internal Module Dependencies

\`\`\`
api → services → models
    ↘ models
\`\`\`

## Security Considerations

1. **Authentication**: JWT-based token authentication
2. **Password Storage**: bcrypt hashing via passlib
3. **CORS**: Configured for specific origins
4. **Rate Limiting**: Implemented via Redis

## Performance Notes

- Connection pooling configured for database
- Redis caching for frequently accessed data
- Async handlers for I/O operations

---

*Report generated by CodeCompass*
`;

const apiDocMarkdown = `# API Documentation

## Authentication Endpoints

### POST /api/auth/login
Authenticate a user and receive access tokens.

**Request Body:**
\`\`\`json
{
  "username": "string",
  "password": "string"
}
\`\`\`

**Response:**
\`\`\`json
{
  "access_token": "string",
  "token_type": "bearer",
  "expires_in": 3600
}
\`\`\`

### POST /api/auth/refresh
Refresh an access token.

**Headers:**
- \`Authorization: Bearer <refresh_token>\`

---

## User Endpoints

### GET /api/users/me
Get the current authenticated user.

**Headers:**
- \`Authorization: Bearer <access_token>\`

**Response:**
\`\`\`json
{
  "id": "uuid",
  "username": "string",
  "email": "string",
  "created_at": "datetime"
}
\`\`\`

### PUT /api/users/me
Update the current user's profile.

---

## Project Endpoints

### GET /api/projects
List all projects.

### POST /api/projects
Create a new project.

### GET /api/projects/{id}
Get a project by ID.

### PUT /api/projects/{id}
Update a project.

### DELETE /api/projects/{id}
Delete a project.

---

*Generated by CodeCompass*
`;

export function ReportsTab() {
  const [activeReport, setActiveReport] = useState<'architecture' | 'api' | 'dependencies'>('architecture');
  const [copied, setCopied] = useState(false);

  const handleCopy = async (content: string) => {
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = (content: string, filename: string) => {
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const reports = [
    {
      id: 'architecture',
      title: 'Architecture Report',
      description: 'Comprehensive overview of the codebase structure and patterns',
      content: architectureMarkdown,
      filename: 'architecture-report.md',
    },
    {
      id: 'api',
      title: 'API Documentation',
      description: 'Auto-generated documentation for API endpoints',
      content: apiDocMarkdown,
      filename: 'api-documentation.md',
    },
    {
      id: 'dependencies',
      title: 'Dependencies Report',
      description: 'Analysis of project dependencies and their relationships',
      content: '',
      filename: 'dependencies-report.md',
    },
  ];

  const currentReport = reports.find(r => r.id === activeReport);

  return (
    <div className="p-6 space-y-6">
      <div>
        <h1 className="text-2xl font-bold">Reports</h1>
        <p className="text-muted-foreground mt-1">
          Auto-generated documentation and analysis reports
        </p>
      </div>

      <Tabs value={activeReport} onValueChange={(v) => setActiveReport(v as any)}>
        <TabsList>
          <TabsTrigger value="architecture">
            <FileText className="h-4 w-4 mr-2" />
            Architecture
          </TabsTrigger>
          <TabsTrigger value="api">
            <ExternalLink className="h-4 w-4 mr-2" />
            API Docs
          </TabsTrigger>
          <TabsTrigger value="dependencies">
            <Package className="h-4 w-4 mr-2" />
            Dependencies
          </TabsTrigger>
        </TabsList>

        <TabsContent value="architecture" className="mt-4">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between">
              <div>
                <CardTitle>Architecture Report</CardTitle>
                <CardDescription>
                  Comprehensive overview of the codebase structure and patterns
                </CardDescription>
              </div>
              <div className="flex items-center gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => handleCopy(architectureMarkdown)}
                >
                  {copied ? <Check className="h-4 w-4 mr-2" /> : <Copy className="h-4 w-4 mr-2" />}
                  Copy
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => handleDownload(architectureMarkdown, 'architecture-report.md')}
                >
                  <Download className="h-4 w-4 mr-2" />
                  Download
                </Button>
              </div>
            </CardHeader>
            <CardContent>
              <ScrollArea className="h-[600px]">
                <div className="prose prose-sm dark:prose-invert max-w-none">
                  <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed">
                    {architectureMarkdown}
                  </pre>
                </div>
              </ScrollArea>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="api" className="mt-4">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between">
              <div>
                <CardTitle>API Documentation</CardTitle>
                <CardDescription>
                  Auto-generated documentation for API endpoints
                </CardDescription>
              </div>
              <div className="flex items-center gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => handleCopy(apiDocMarkdown)}
                >
                  {copied ? <Check className="h-4 w-4 mr-2" /> : <Copy className="h-4 w-4 mr-2" />}
                  Copy
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => handleDownload(apiDocMarkdown, 'api-documentation.md')}
                >
                  <Download className="h-4 w-4 mr-2" />
                  Download
                </Button>
              </div>
            </CardHeader>
            <CardContent>
              <ScrollArea className="h-[600px]">
                <div className="prose prose-sm dark:prose-invert max-w-none">
                  <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed">
                    {apiDocMarkdown}
                  </pre>
                </div>
              </ScrollArea>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="dependencies" className="mt-4">
          <Card>
            <CardHeader>
              <CardTitle>Dependencies Report</CardTitle>
              <CardDescription>
                Analysis of project dependencies and their relationships
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-6">
                {/* External Dependencies */}
                <div>
                  <h3 className="font-semibold mb-3">External Dependencies</h3>
                  <div className="grid grid-cols-2 gap-3">
                    {mockArchitectureReport.dependencies.external.map((dep) => (
                      <div
                        key={dep.name}
                        className="flex items-center justify-between p-3 rounded-lg bg-muted/50"
                      >
                        <div className="flex items-center gap-2">
                          <Package className="h-4 w-4 text-muted-foreground" />
                          <span className="font-mono text-sm">{dep.name}</span>
                        </div>
                        <Badge variant="secondary">{dep.version}</Badge>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Internal Dependencies */}
                <div>
                  <h3 className="font-semibold mb-3">Internal Module Dependencies</h3>
                  <div className="space-y-2">
                    {mockArchitectureReport.dependencies.internal.map((dep) => (
                      <div
                        key={dep.module}
                        className="flex items-center gap-3 p-3 rounded-lg bg-muted/50"
                      >
                        <Badge variant="default">{dep.module}</Badge>
                        {dep.dependsOn.length > 0 ? (
                          <>
                            <span className="text-muted-foreground">→</span>
                            {dep.dependsOn.map((d) => (
                              <Badge key={d} variant="outline">{d}</Badge>
                            ))}
                          </>
                        ) : (
                          <span className="text-sm text-muted-foreground">No dependencies</span>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
